services:
  app:
    build:
      context: .
    image: next-js-dev
    ports:
    - "3000:3000"
    environment:
      NODE_ENV: development
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"